import io
import sys

_INPUT = """\
6
##.......
##.......
.........
.......#.
.....#...
........#
......#..
.........
.........
.#.......
#.#......
.#.......
.........
....#.#.#
.........
....#.#.#
........#
.........
"""

sys.stdin = io.StringIO(_INPUT)
case_no=int(input())
for __ in range(case_no):
  S=[input() for _ in range(9)]
  ans=0
  for i in range(9):
    for j in range(9):
      if S[i][j]=='.': continue
      for k in range(9):
        for l in range(1,9):
          if 0<=i+k<9 and 0<=j+l<9 and 0<=i+k+l<9 and 0<=j+l-k<9 and 0<=i+l<9 and 0<=j-k<9 and S[i+k][j+l]=='#' and S[i+k+l][j+l-k]=='#' and S[i+l][j-k]=='#': ans+=1
  print(ans)